md "dist\assets\avatars"
copy "pics\avatars" "dist\assets\avatars"
copy "pics\icon.png" "dist\assets\"
copy "install.htm" "dist\"
copy "install.js" "dist\"
copy "src\assets\install_notes.png" "dist\assets\"
copy "src\assets\icon128.png" "dist\assets\"
